# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLcGMq-dAnquGeYG8FS1LmUzfPm2irQl
"""

!nvidia-smi

import tensorflow as tf
print(tf.__version__)

from google.colab import drive
drive.mount('/gdrive')

!pip install face_recognition opencv_python matplotlib

import cv2,os
import face_recognition as fr
from IPython.display import Image,display
from matplotlib import pyplot as plt

image_path='/gdrive/My Drive/svt.jpg'
image=fr.load_image_file(image_path)
plt.imshow(image)
plt.show

face_locations=fr.face_locations(image)

for(top,right,bottom,left)in face_locations:
    cv2.rectangle(image,(left,top),(right,bottom),(0,255,0),3)

plt.rcParams['figure.figsize']=(16,16)
plt.imshow(image)
plt.show()